markdown: kramdown
highlighter: rouge

permalink: /:title
name: "@xixi003"

author: "@xixi003"
atom-baseurl: "http://yijia.ws"
disqus: "yijia2413"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Github
    class: fa fa-github
    href: https://www.github.com/yijia2413
  - title: Linkedin
    class: fa fa-linkedin
    href: https://www.linkedin.com/in/yijia2413
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

kramdown:
  input: GFM
  hard_wrap: false