permalink: /:title
paginate: 10
author: 
  name: 一小佳
  email: yijia2413@gmail.com
  link: http://yijia2413.github.io/
title: 一小佳
locals:
  tags: tags
  about: about
active: blog
subscribe_rss: /pages/atom.xml
markdown: redcarpet

