markdown: rdiscount
permalink: /:title/
url: http://yijia2413.github.io
name: 一小佳
author: 一小佳
email: yijia2413@gmail.com 
duoshuo: yijia2413
github: yijia2413
pygments: true
safe: true
paginate: 20
about: {{ site.about }}
