permalink: /:title
paginate: 10
author: 
  name: 一小佳
  email: yijia2413@gmail.com
  link: http://yijia2413.github.io/
title: 一小佳
locals:
  tags: 标签
  about: 关于
active: 博客
subscribe_rss: /pages/atom.xml
markdown: redcarpet

