# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: rouge
markdown: kramdown


# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title :  "@xixi003"
tagline:
author :
  name :

#
production_url : http://yijia.ws


# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

  BASE_PATH : http://yijia.ws
  BLOG_PATH : http://yijia.ws

  sharing :
    provider : false
